"""
Key Management Routes — CRUD and rotation for encryption keys.
"""

from flask import Blueprint, request, jsonify, session
from routes.auth import login_required, role_required
from core.key_manager import KeyManager
from core.audit_logger import AuditLogger

keys_bp = Blueprint('keys', __name__)


@keys_bp.route('/api/keys', methods=['GET'])
@login_required
def get_keys():
    keys = KeyManager.get_all_keys()
    return jsonify({'keys': [k.to_dict() for k in keys]})


@keys_bp.route('/api/keys', methods=['POST'])
@login_required
@role_required('admin')
def create_key():
    data = request.get_json() or {}
    name = data.get('name', 'unnamed-key')
    expires_in = data.get('expires_in_days', 30)

    key = KeyManager.generate_key(
        name=name,
        created_by=session.get('user_id'),
        expires_in_days=expires_in
    )

    username = session.get('username')
    AuditLogger.log(
        'KEY_GENERATE',
        f'New key "{name}" generated by {username}',
        source_ip=request.remote_addr,
        user_id=session.get('user_id')
    )

    return jsonify({'success': True, 'key': key.to_dict()}), 201


@keys_bp.route('/api/keys/<int:key_id>', methods=['DELETE'])
@login_required
@role_required('admin')
def delete_key(key_id):
    key = KeyManager.get_key_by_id(key_id)
    if not key:
        return jsonify({'error': 'Key not found'}), 404

    key_name = key.key_name
    KeyManager.delete_key(key_id)

    username = session.get('username')
    AuditLogger.log(
        'KEY_DELETE',
        f'Key "{key_name}" (ID:{key_id}) deleted by {username}',
        source_ip=request.remote_addr,
        user_id=session.get('user_id')
    )

    return jsonify({'success': True})


@keys_bp.route('/api/keys/<int:key_id>/deactivate', methods=['POST'])
@login_required
@role_required('admin')
def deactivate_key(key_id):
    key = KeyManager.get_key_by_id(key_id)
    if not key:
        return jsonify({'error': 'Key not found'}), 404

    KeyManager.deactivate_key(key_id)

    username = session.get('username')
    AuditLogger.log(
        'KEY_DEACTIVATE',
        f'Key "{key.key_name}" deactivated by {username}',
        source_ip=request.remote_addr,
        user_id=session.get('user_id')
    )

    return jsonify({'success': True})


@keys_bp.route('/api/keys/rotate', methods=['POST'])
@login_required
@role_required('admin')
def rotate_keys():
    new_key = KeyManager.rotate_key(created_by=session.get('user_id'))

    username = session.get('username')
    AuditLogger.log(
        'KEY_ROTATE',
        f'Key rotation performed by {username}. New key: {new_key.key_name}',
        source_ip=request.remote_addr,
        user_id=session.get('user_id')
    )

    return jsonify({'success': True, 'key': new_key.to_dict()})


@keys_bp.route('/api/keys/stats', methods=['GET'])
@login_required
def key_stats():
    stats = KeyManager.get_key_stats()
    return jsonify(stats)
